name: "Github Release 422"
author: "Junaid Rasheed"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Github releases from an action. Handles 422s from GitHub."

inputs:
  title:
    description: "The name of the release to publish"
    required: true
  workdir:
    description: "Directory of the repository that the should create the release"
    required: false
  tag:
    description: "The tag of the release to publish"
    required: false

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_TAG: ${{ inputs.tag }}
